### ISSUE TITLE
[Bug] Springboard quits cause of Koi if you force touch on something that isn’t an app

### ISSUE THREAD

**Issue by TheAwesome98-Real** [woodfairy/koi#6]
If you force touch on a web clip, it quits springboard, most likely cause libKitten doesn’t know what the heck the icon is supposed to be. Maybe a workaround is to just set it to default colour?

**Comment by woodfairy** [comment]
I will look into it as soon as I can

**Comment by TheAwesome98-Real** [comment]
Thanks!

**Comment by woodfairy** [comment]
This bug has been fixed. In the next release this will be shipped with full iOS 14 support and more cool stuff!

**Comment by TheAwesome98-Real** [comment]
> This bug has been fixed. In the next release this will be shipped with full iOS 14 support and more cool stuff!

Thanks so much! I’ll reenable koi from system preferences! :)
